baseurl = "http://handstodur.is"
title = "Handstöðu Helgi"
theme = "dimension"
languageCode = "en-is"
defaultContentLanguage = "is"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Handstöðukennsla!<!--]-->'
  logoimage = "/images/8bit-circle - b&w.png"
  copyright = "Helgi"
  custom_css = ["css/custom.css"]

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "http://instagram.com/helgi_freyr"
  
[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/HandstoduHelgi/"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:helgi@primal.is"

[languages]
[languages.is]
languageName = "Íslenska"
weight = 1
title = "Lærðu að standa á höndum! bla bla bla"
baseurl = "http://handstodur.is"
description = '<!--[-->Námskeið, einkatímar, fjarþjálfun og vikulegir ástundunartímar <br><br>Helgi Freyr, eigandi og þjálfari <a href="http://primal.is">Primal Iceland</a>, býður upp á handstöðukennslu sem hentar öllum <br><br> Hvort sem að þú ert byrjandi, kannt að standa á höndum eða einfaldlega forvitin, þá get ég hjálpað þér<!--]-->'